export const cars = [
  {
    id: 1,
    image: "https://wallpapers.com/images/hd/toyota-fortuner-2022-legender-379k2uid45og6yr6.jpg",
    name: "Fortuner Legender",
    description: "Electric luxury sedan with long range and cutting-edge technology.",
    price: "$89,990",
    rating: 4.9,
  },
  {
    id: 2,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqFQMnFedmWmWabOyK36Vumk2VXoYOgQhmUA&s",
    name: "BMW 7 Series",
    description: "Premium luxury sedan offering comfort and performance.",
    price: "$86,800",
    rating: 4.8,
  },
  {
    id: 3,
    image: "https://images.unsplash.com/photo-1617195920950-1145bf9a9c72?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8YXVkaSUyMGNhcnxlbnwwfHwwfHx8MA%3D%3D",
    name: "Audi RS5",
    description: "Sporty performance coupe with a powerful engine and sharp design.",
    price: "$75,400",
    rating: 4.7,
  },
  {
    id: 4,
    image: "https://img.autocarpro.in/autocarpro/7cc112d3-6669-47dc-8f2a-ebe78c42de27.png?w=750&h=490&q=75&c=1",
    name: "Mercedes AMG E63",
    description: "High-performance luxury sedan with  premium comfort.",
    price: "$107,500",
    rating: 4.9,
  },
  {
    id: 5,
    image: "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Porsche 911",
    description: "Iconic sports car blending speed, design, and driving experience.",
    price: "$114,000",
    rating: 5.0,
  },
  {
    id: 6,
    image: "https://images.pexels.com/photos/3752169/pexels-photo-3752169.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Rolls Royce Ghost",
    description: "The epitome of luxury and craftsmanship with unparalleled comfort.",
    price: "$315,000",
    rating: 5.0,
  },
  {
    id: 7,
    image: "https://images.pexels.com/photos/1402787/pexels-photo-1402787.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Lamborghini Huracan",
    description: "Exotic supercar with aggressive styling and roaring V10 engine.",
    price: "$210,000",
    rating: 4.9,
  },
  {
    id: 8,
    image: "https://images.pexels.com/photos/1719644/pexels-photo-1719644.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Ferrari F8 Tributo",
    description: "Mid-engine Italian supercar with stunning performance and handling.",
    price: "$276,550",
    rating: 4.8,
  },
  {
    id: 9,
    image: "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "McLaren 720S",
    description: "Lightweight British supercar with twin-turbo V8 and sleek design.",
    price: "$299,000",
    rating: 4.9,
  },
  {
    id: 10,
    image: "https://images.pexels.com/photos/1149831/pexels-photo-1149831.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Bugatti Chiron",
    description: "Hypercar with quad-turbo W16 engine and unmatched top speed.",
    price: "$3,000,000",
    rating: 5.0,
  },
  {
    id: 11,
    image: "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Jaguar F-Type",
    description: "Stylish British sports car with thrilling performance.",
    price: "$73,400",
    rating: 4.6,
  },
  {
    id: 12,
    image: "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Aston Martin DB11",
    description: "Grand tourer with iconic design and V12 engine power.",
    price: "$205,600",
    rating: 4.8,
  },
  {
    id: 13,
    image: "https://images.pexels.com/photos/799443/pexels-photo-799443.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Maserati Levante",
    description: "Luxury Italian SUV combining elegance with performance.",
    price: "$102,500",
    rating: 4.7,
  },
  {
    id: 14,
    image: "https://images.pexels.com/photos/3752169/pexels-photo-3752169.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Bentley Continental GT",
    description: "Luxury grand tourer with unmatched comfort and twin-turbo W12.",
    price: "$218,350",
    rating: 5.0,
  },
  {
    id: 15,
    image: "https://images.pexels.com/photos/1149831/pexels-photo-1149831.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Koenigsegg Agera RS",
    description: "Swedish hypercar with extreme performance and engineering excellence.",
    price: "$2,500,000",
    rating: 5.0,
  },
  {
    id: 16,
    image: "https://images.pexels.com/photos/1719644/pexels-photo-1719644.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Pagani Huayra",
    description: "Exotic handcrafted hypercar with AMG engine and stunning design.",
    price: "$3,200,000",
    rating: 5.0,
  },
  {
    id: 17,
    image: "https://images.pexels.com/photos/210019/pexels-photo-210019.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Lexus LC 500",
    description: "Luxury coupe blending Japanese craftsmanship and a V8 engine.",
    price: "$98,850",
    rating: 4.7,
  },
  {
    id: 18,
    image: "https://images.pexels.com/photos/1402787/pexels-photo-1402787.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Nissan GT-R",
    description: "Legendary Japanese sports car nicknamed 'Godzilla'.",
    price: "$113,540",
    rating: 4.8,
  },
  {
    id: 19,
    image: "https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Chevrolet Corvette C8",
    description: "American mid-engine sports car delivering supercar performance at value.",
    price: "$65,900",
    rating: 4.9,
  },
  {
    id: 20,
    image: "https://images.pexels.com/photos/358070/pexels-photo-358070.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Ford Mustang GT",
    description: "Iconic American muscle car with a 5.0L V8 engine.",
    price: "$55,300",
    rating: 4.7,
  },
];
